theme: jekyll-theme-slate

gem "github-pages", group: :jekyll_plugins


title: [SSH KEY AGGREGATOR]
description: [Aggregate an SSH key to Deploy-Keys section of the specified
Github repository. The private part is displayed on the screen in base64 format.]


show_downloads: [true]
